name: PR Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SPECS_TOKEN }}
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.21

      - uses: actions/setup-node@v1
        with:
          node-version: '20.x'

      - name: Test build
        env:
          TARGET_URL: "https://docs.flashbots.net"
          BASE_URL: "/"
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Check for broken links
        run: |
          go install github.com/raviqqe/muffet/v2@latest

          echo -e "BASE_URL=/docs/\nTARGET_URL=http://localhost:3000" > .env
          yarn serve &
          sleep 5
          echo "Checking for broken links..."
          muffet http://localhost:3000/docs/ \
            --exclude="notion[.]so" \
            -e "github[.]com/flashbots/suave-specs" \
            -e "github[.]com/flashbots/suave-bridge" \
            -e "algolia[.]net"
