name: PR Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SPECS_TOKEN }}
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.21

      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'yarn'

      - name: Installing dependencies
        run: yarn install --frozen-lockfile

      - name: Building the docs
        env:
          TARGET_URL: "http://localhost:3000"
          BASE_URL: "/docs/"
        run: yarn build

      - name: Check for broken links
        env:
          TARGET_URL: "http://localhost:3000"
          BASE_URL: "/docs/"
        run: |
          go install github.com/raviqqe/muffet/v2@latest

          yarn serve &
          sleep 5

          echo "Checking for broken links..."
          muffet --version
          muffet http://localhost:3000/docs/ \
            --ignore-fragments \
            --skip-tls-verification \
            --buffer-size=16384 \
            --exclude="notion[.]so" \
            -e "algolia[.]net" \
            -e "arxiv[.]org" \
            -e "docs[.]google[.]com/presentation/d/19km1xqXrp6HClAOmyUwtq7lADM7BEUsPbTUE7zCwhCw" \
            -e "pathoram[.]jimdofree[.]com/files/" \
            -e "flashbots[.]notion[.]site" \
            -e "https://github.com/flashbots/suave-docs" \
            -e "https://github.com/flashbots/suave-bridge" \
            -e "https://github.com/flashbots/suave-specs" \
            -e "https://github.com/flashbots/suapp-examples" \
            -e "https://github.com/flashbots/suave-viem" \
            -e "https://suave.flashbots.net"
