name: PR Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.21

      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Installing dependencies
        run: npm install

      - name: Building the docs
        env:
          TARGET_URL: 'http://localhost:3000'
          BASE_URL: '/docs/'
          ALGOLIA_APP_ID: 'example'
          ALGOLIA_SEARCH_API_KEY: 'example'
          ALGOLIA_INDEX_NAME: 'example'
        run: npm run build

      - name: Check for broken links
        env:
          TARGET_URL: 'http://localhost:3000'
          BASE_URL: '/docs/'
        run: |
          go install github.com/raviqqe/muffet/v2@latest

          npm serve &
          sleep 5

          echo "Checking for broken links..."
          muffet --version
          muffet http://localhost:3000/docs/ \
            --ignore-fragments \
            --skip-tls-verification \
            --buffer-size=16384 \
            -e "algolia[.]net" \
            -e "arxiv[.]org" \
            -e "https://github.com/flashbots/suave-docs" \
            -e "https://github.com/flashbots/suave-bridge" \
            -e "https://suave.flashbots.net"
