name: SuaveLib sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  sync-suave-std-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.21

      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: flashbots/suave-std
          path: suave-std
          persist-credentials: false
          fetch-depth: 0

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Build the contracts
        run: |
          cd suave-std
          forge install
          forge build

      - name: Run docs generator
        run: |
          cd suave-std/tools/docs-gen
          go run main.go --suave-std ../../ --out ../../../docs/tools/suave-std

      - name: Add changes to git
        run: |
          rm -rf suave-std
          git add ./docs/tools/suave-std

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "Update Suave-std api reference"
          delete-branch: true
          commit-message: Update Suave-std api reference ${{ steps.get_commit_id.outputs.commit_ref }}
          branch: bot/suave-lib-update
          labels: |
            suave-lib-update
            automated pr
          body: |
            Update Suave-std api reference ${{ steps.get_commit_id.outputs.commit_ref }}